# Generated by Django 3.1.6 on 2021-06-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20210623_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Colours',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model', 'car_colour']},
        ),
        migrations.AddField(
            model_name='car',
            name='car_colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car.colour'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.colour'),
        ),
    ]
